jobs/urls.py
from django.urls import path, re_path

from .views import jobs_view, jobDetail, jobDelete , resumeDelete

app_name = 'jobs'

urlpatterns = [
	path('jobs/', jobs_view, name='jobs'),
	path('job/<int:pk>', jobDetail, name='jobDetail'),
	path('job/delete/<int:pk>', jobDelete, name='jobDelete'),
	path('job/<int:jid>/resume/delete/<int:rid>', resumeDelete, name='resumeDelete')
	
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('', include('jobs.urls', namespace='jobs')),
    path('profile/', include('profiles.urls', namespace='profiles')),
]

urlpatterns += [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
]

jobs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Job(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=1000, blank=True)
    job_description = models.CharField(max_length=2000)
    skills = models.CharField(default=False,max_length=2000)
    status = models.CharField(default="NotScored",max_length=10)
class Resume(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    email = models.EmailField()
    skills = models.CharField(max_length=1000)
    score = models.DecimalField(default=0 , decimal_places=2 , max_digits=4)
    resume_data = models.CharField(max_length=5000)
    #id = models.AutoField(primary_key=True)
    status = models.CharField(default="Not Shared",max_length=10)

jobs/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from jobs.models import Jobs

class JobsForm():
    title = forms.CharField(
        label='Software Developer',
        max_length=254,
        required=True,
    )

    job_description = forms.TextInput(
        label='',
        max_length=2000,
        min_length=50,
        required=True,
    )

    skills = forms.CharField(
        label='',
        max_length=100,
        min_length=1,
        required=True,
    )
    
    class Meta:
        model = Jobs
        fields = ('title', 'job_description', 'skills', "status")

jobs/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Job , Resume

from django.shortcuts import redirect

from django.core.serializers import serialize
from django.http import JsonResponse
import json
import PyPDF2, re, docx2txt
# Create your views here.


@login_required
def jobs_view(request):
    
    if request.method == "GET":
        jobs = list(Job.objects.filter(user=request.user).values())
        print(jobs)
        return render(request, 'app/jobs.html',{"jobs":jobs})
    
    if request.method == "POST":
        title = request.POST.get("title")
        job_description = request.POST.get("job_description")
        skills = request.POST.get("skills")
        insertObject = Job.objects.create(user=request.user,title=title,job_description=job_description,skills=skills)
        jobs = list(Job.objects.filter(user=request.user).values())
        return render(request, 'app/jobs.html',{"jobs":jobs})

@login_required
def jobDetail(request, pk):
    if request.method == "GET":
        current_job = Job.objects.get(user=request.user,id=pk)
        job = list(Job.objects.filter(user=request.user, id=pk).values())[0]
        resumes = list(Resume.objects.filter(job=current_job).values())
        return render(request, 'app/job.html',{"job": job,"resumes":resumes})
    
    if request.method == "POST":
        current_job = Job.objects.get(user=request.user,id=pk)
        job = list(Job.objects.filter(user=request.user, id=pk).values())[0]
        for f in request.FILES.getlist('files'):
            exist , email, matchedSkills, data = fetchData(f,job['skills'], pk)
            if  exist :
                Resume.objects.create(job=current_job,email=email,skills=matchedSkills,resume_data=data)
        resumes = list(Resume.objects.filter(job=current_job).values())
        return render(request, 'app/job.html',{"job": job,"resumes":resumes})

    
@login_required
def jobDelete(request, pk):
    Job.objects.filter(id=pk).delete()
    jobs = list(Job.objects.filter(user=request.user).values())
    return redirect('/jobs')
    
    #return render(request, 'app/jobs.html',{"jobs":jobs})


def fetchData(resume, skills , pk):
    
    skills = skills.split(",")
    data = ""
    
    if resume.name[-3:].lower() == "pdf" :
        pdfReader = PyPDF2.PdfFileReader(resume.file)
        number_of_pages = pdfReader.getNumPages()
        for page in range(number_of_pages):
            page = pdfReader.getPage(page)
            data += page.extractText()
        email = re.search(r'[\w\.-]+@[\w\.-]+', data).group(0)
        matchedSkills = ",".join([skill for skill in skills if skill.lower() in data.lower()])
        if Resume.objects.filter(email=email , job=pk).exists():
            return False , email , matchedSkills , data 
        else :
            return True ,email, matchedSkills, data  


    if resume.name[-4:].lower() == "docx":
        data = docx2txt.process(resume.file)

        email = re.search(r'[\w\.-]+@[\w\.-]+', data).group(0)
        matchedSkills = ",".join([skill for skill in skills if skill.lower() in data.lower()])
        if Resume.objects.filter(email=email , job=pk).exists():
            return False , email , matchedSkills , data 
        else :
            return True , email, matchedSkills, data


@login_required
def resumeDelete(request, jid , rid):
    Resume.objects.filter(id=rid).delete()
    return redirect('/job/{}'.format(jid))
    
    #return render(request, 'app/jobs.html',{"jobs":jobs})


       
      
  

templates/app/home.html
{% extends "base.html" %}

{% block title %}
	Home
{% endblock %}
  
 


{% block content %}

<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">

  <div class="container">
    <div class="row">
      <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
        <h1>Resume_Ranker</h1>
        <h2>Your time is priceless , Spent it wisley.</h2>
        
       <b>&nbsp; &nbsp; &nbsp;"We save your time <Br>&nbsp; &nbsp; &nbsp;
        &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;Select The BEST from best"</b> 
    </p>
        <div class="d-lg-flex">
          <a href="#about" class="btn-get-started scrollto">Get Started</a>
         
        </div>
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
        <img src="../../static/img/myimg/hero-img.png" class="img-fluid animated" alt="">
      </div>
    </div>
  </div>

</section><!-- End Hero -->

<main id="main">

  <!-- ======= Cliens Section ======= -->
  <section id="cliens" class="cliens section-bg">
    <div class="container">

      </div>

    </div>
  </section><!-- End Cliens Section -->

 
    <!-- ======= App Features Section ======= -->
    <section id="features" class="features">
      <div class="container">

        <div class="section-title">
          <h2> Features</h2>
          <p>Your time is priceless  And Therefore here
            we score the resume on the basis of  job description provided by you and show 
            you those resume  which are more deserving . some of our features are 
          </p>
        </div>
        <div class="row no-gutters">
          <div class="col-md-8">
          <div class="col-xl-7 d-flex align-items-stretch order-2 order-lg-1">
            <div class="content d-flex flex-column justify-content-center">
              <div class="row">
                <div class="col-md-6 icon-box" data-aos="fade-up">
                  <i class="bx bx-receipt"></i>
                  <h4>Resumes</h4>
                  <p>A resume is a formal document that a job applicant creates to itemize his or her qualifications for a position.</p>
                </div>
               <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="200">
                  <i class="bx bx-images"></i>
                  <h4>Job </h4>
                  <p>HR creates Jobs with Titles and Descriptions.</p>
                </div>
               
                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="500">
                  <i class="bx bx-id-card"></i>
                  <h4>Scoring</h4>
                  <p>In it,Resume will be scored on the basis of skills as per the jd require.</p>
                </div>
                <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
                  <i class="bx bx-shield"></i>
                  <h4>Security</h4>
                  <p>There is no security.</p>
                </div>
              </div>
            </div>
          </div></div>
          <div class="col-md-4" data-aos="fade-right" data-aos-delay="100">
            <img src="../../static/img/details/features.svg" class="img-fluid" alt="">
          </div>
        </div>
       

      </div>
    </section><!-- End App Features Section -->

  <!-- ======= Details Section ======= -->
  <section id="details" class="details">
    <div class="container">

      <div class="row content">
        <div class="col-md-4" data-aos="fade-right">
          <img src="../../static/img/details/details-1.png" class="img-fluid" alt="">
        </div>
        <div class="col-md-8 pt-4" data-aos="fade-up">
          <h3>WHAT DOES IT WORK ?</h3><br>
          <p class="font-italic">
            
          <li>Resume ranker scores the resume that are given by HR as per the Job Descripstion required.</li><br>
          <li>It puts those Resumes that are fesiable for the JD on the top priority.</li><br>
          <li>Then ,HR will recheck the resumes whether they are best for the JD or not then HR will assign whether they shared , not shared or rejected.</li>
        
          </p>
         
          <p>
           
          </p>
        </div>
      </div>

      <div class="row content">
        <div class="col-md-4 order-1 order-md-2" data-aos="fade-left">
          <img src="../../static/img/details/details-2.png" class="img-fluid" alt="">
        </div>
        <div class="col-md-8 pt-5 order-2 order-md-1" data-aos="fade-up">
          <h3>HOW IT WORKS ?</h3><br>
          <p class="font-italic">
          
            <li><i class="icofont-check"></i>Firstly,HR collects the resumes as per the JD requires.</li><br>
            <li><i class="icofont-check"></i>Then,HR creates the Jobs and fill the Descriptions.</li><br>
            <li><i class="icofont-check"></i>Now HR will upload all the resumes for the job.</li><br>
            <li><i class="icofont-check"></i>Then, Our website will prioritize those resumes that are best for JD.</li>
          
</p>
        </div>
      </div>

    </div>
  </section><!-- End Details Section -->


</main>


  <!-- ======= Footer ======= -->
  <footer id="footer">

   

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Team08</h3>
            <p>
              GLA University <br>
              Mathura, 17km NH2<br>
              India <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> Team08@gmail.com<br>
            </p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Features</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Registration</a></li>
              
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Scoring Resumes</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Ranking</a></li>
              
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Contact Us</h4>
            <p>You can follow us on :</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
             
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container footer-bottom clearfix">
      <div class="copyright">
        &copy; Copyright <strong><span>Team08</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        
        Designed & Developed  by <a href="#">Team08 </a>
      </div>
    </div>
  </footer><!-- End Footer -->
 
{% endblock content %}

templates/app/job.html
{% extends "base.html" %}

{% block title %}
	Dashboard
{% endblock %}
{% block head %}
<meta http-equiv="refresh" content="20"/>
{% endblock %}
{% block content %}

	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-success mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}
	
<h1> {{ job.title }} </h1>
<form method="post" enctype="multipart/form-data" action="/job/{{ job.id }}"> 
	{% csrf_token %}
	<input type="file" id="files" name="files" multiple/>
	<input type="submit" value="Upload" />

	<button type="button" id="btn" class=" btn-sm">Score</button>

	</form>

	{% if resumes|length == 0 %}
	
	<h1> No Data Found </h1>
	
	{% else %}

	<h4><span style="color: rgb(2, 11, 19);"> Created jobs :</span></h4>
	<table class="table table-striped" id="job">
  <thead>
    <tr style="background-color:rgb(206, 177, 207);">
      <th scope="col">Email</th>
      <th scope="col">Matched Skills</th>
	  <th scope="col">Score</th>
	  <th scope="col">Status</th>
	  <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  {% for resume in resumes %}
    <tr>
		<td>{{ resume.email}}</td>
      <td>{{ resume.skills }}</td>
	  <td>{{ resume.score }}</td>
	  <td>
		<input list="status" name="status">
		<datalist id="status">
		  <option value="Selected"></option>
		  <option value="Rejected"></option>
		  <option value="Not Shared"></option>
		</datalist>
	  </td>
	  <td>
		<form action="{% url 'jobs:resumeDelete' job.id resume.id %}" method="POST">
		{% csrf_token %}
		<button type="submit">Delete</button>
		</form>
	   </td>
    </tr>
  {% endfor %}
    
  </tbody>
</table>
<script>
	$(document).ready(function() {
	  $('#job').DataTable();
	} );
</script>
{% endif %}
{% endblock content %}

templates/app/jobs.html
{% extends "base.html" %}

{% block title %}
  Dashboard
 
{% endblock %}
{% block head %}
<meta http-equiv="refresh" content="30"/>
{% endblock %}
{% block content %}

	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-success mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}
	
<div class="container">
    <div class="row">
    <div class="col-sm-8">

                <h4 class="page-header">Create Job</h4>
                <form role="form" method="post">
                {% csrf_token %}
                    <div class="form-group float-label-control">
                        <label for="">Title</label>
                        <input id="title" name="title" type="text" class="form-control w-50 p-3" placeholder="Title" >
                    </div>
                    <div class="form-group float-label-control">
                        <label for="">Job Description</label>
                        <textarea id="job_description" name="job_description" class="form-control w-50 p-3" placeholder="Job Description" rows="1"></textarea>
                    </div>
                    <div class="form-group float-label-control">
                    <label for="">Skills</label>
                    <input id="skills" name="skills" type="text"  class="form-control w-50 p-3" value="jQuery,Script,Net">
                    </div>
                    <button class="btn btn-secondary float-left" type="submit">Create</button>
                </div>
                </form>
    </div>
    </div>

	<br>
	<br>
	
	{% if jobs|length == 0 %}
	
	<h1> No Data Found </h1>
	
	{% else %}
	<h4><span style="color: rgb(2, 11, 19);"> Created jobs :</span></h4>
	<table class="table table-striped" id="jobs">
  <thead>
    <tr style="background-color:rgb(206, 177, 207);">
      <th scope="col">Job Name</th>
      <th scope="col">Skills</th>
      <th scope="col">Score</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  {% for job in jobs %}
    <tr>
      <td  style="color: rgb(0, 119, 255);"><a href="{% url 'jobs:jobDetail' job.id %}">{{ job.title }}</a></td>
      <td>{{ job.skills }}</td>
      <td style="color: rgb(26, 2, 27);">{{ job.status }}</td>
      <td>
       <form action="{% url 'jobs:jobDelete' job.id %}" method="POST">
       {% csrf_token %}
       <button type="submit">Delete</button>
       </form>
      </td>
    </tr>
  {% endfor %}
    
  </tbody>
</table>

<script>
$(document).ready(function() {
  $('#jobs').DataTable();
} );
</script>
{% endif %}

{% endblock content %}

templates/app/profile_edit.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
	Edit Bio
{% endblock %}

{% block content %}
	
	<div class="text-left mt-5 container">
		{% for field in form %}
		    <p>
	        	{{ field.label_tag }}
	        	{{ field|attr:"rows:20"|attr:"cols:20" }}
		       {% if field.help_text %}
		          <small style="color: grey">{{ field.help_text }}</small>
		        {% endif %} 
		        {% for error in field.errors %}
		          <p style="color: red">{{ error }}</p>
		        {% endfor %}
		    </p>
		{% endfor %}
	</div>


	<div class="container rounded bg-white mt-5 mb-5">
		<div class="row">
			<div class="col-md-3 border-right">
				<div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" src="https://i.imgur.com/O1RmJXT.jpg" width="90"><span class="font-weight-bold">John Doe</span><span class="text-black-50">john_doe12@bbb.com</span><span>United States</span></div>
			</div>
			<div class="col-md-5 border-right">
				<div class="p-3 py-5">
					<div class="d-flex justify-content-between align-items-center mb-3">
						<h6 class="text-right">Edit your profile</h6>
					</div>
					<div class="row mt-2">
						<div class="col-md-6"><label class="labels">UserName</label><input type="text" class="form-control" placeholder="first name" value="John"></div>
					</div>
					<div class="row mt-3">
						<div class="col-md-12"><label class="labels">Email</label><input type="email" class="form-control" placeholder="Email" value="your@email.com"></div>
						<div class="col-md-12"><label class="labels"> Password</label><input type="password" class="form-control" placeholder="Pass" value="Passw0rd"></div>
						<div class="col-md-12"><label class="labels">New Password</label><input type="password" class="form-control" placeholder="Pass" value="Passw0rd"></div>
					</div>
					<div class="row mt-3">
						<div class="col-md-6"><label class="labels">LOcation</label><input type="text" class="form-control" placeholder="LOcation" value="Delhi"></div>
					</div>
					<div class="mt-5 text-center"><button class="btn btn-primary profile-button" type="button">Save Profile</button></div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="p-3 py-5">
					<div class="d-flex justify-content-between align-items-center experience"><span>Edit Experience</span><span class="border px-3 p-1 add-experience"><i class="fa fa-plus"></i>&nbsp;Experience</span></div>
					<div class="d-flex flex-row mt-3 exp-container"><img src="https://i.imgur.com/azSfBM3.png" width="45" height="45">
						<div class="work-experience ml-1"><span class="font-weight-bold d-block">Senior UI/UX Designer</span><span class="d-block text-black-50 labels">Twitter Inc.</span><span class="d-block text-black-50 labels">March,2017 - May 2020</span></div>
					</div>
					<hr>
					<div class="d-flex flex-row mt-3 exp-container"><img src="https://img.icons8.com/color/100/000000/facebook.png" width="45" height="45">
						<div class="work-experience ml-1"><span class="font-weight-bold d-block">Senior UI/UX Designer</span><span class="d-block text-black-50 labels">Facebook Inc.</span><span class="d-block text-black-50 labels">March,2017 - May 2020</span></div>
					</div>
					<hr>
					<div class="d-flex flex-row mt-3 exp-container"><img src="https://img.icons8.com/color/50/000000/google-logo.png" width="45" height="45">
						<div class="work-experience ml-1"><span class="font-weight-bold d-block">UI/UX Designer</span><span class="d-block text-black-50 labels">Google Inc.</span><span class="d-block text-black-50 labels">March,2017 - May 2020</span></div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/app/signup.html
{% extends "base.html" %}

{% block title %}
	Sign Up
{% endblock %}

{% block content %}
	
	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-danger mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}

<div class="container mt-4">
<div class="row">
	

		<div class="col-md-2"></div>

	<div class="col-md-4">
		<!-- Default form register -->
		<form class="border mt-5 border-secondary text-center p-3" method="post">
			{% csrf_token %}
		    <p class="h4 mb-4 text-secondary text-center">Sign Up</p>

		    <!-- {{ form.as_p }} -->

			{% for field in form %}
		    <p>
	        	{{ field.label_tag }}
	        	{{ field }}
		        <!-- {% if field.help_text %}
		          <small style="color: grey">{{ field.help_text }}</small>
		        {% endif %} -->
		        {% for error in field.errors %}
		          <p style="color: red">{{ error }}</p>
		        {% endfor %}
		    </p>
		    {% endfor %}

		    <!-- Sign up button -->
		    <button class="btn btn-secondary my-4 btn-block" type="submit">Sign up</button>

		    

		    <hr>

		    <!-- Terms of service -->
		    <p>By clicking
		        <em>Sign up</em> you agree to our
		        <a href="" target="_blank">terms of service</a>
		    </p>
		</form>
		<!-- Default form register -->
	</div>

	<div class="col-md-2"></div>

</div>
</div>


{% endblock %}