jobs/urls.py
from django.urls import path, re_path

from .views import jobs_view, jobDetail, jobDelete , resumeDelete

app_name = 'jobs'

urlpatterns = [
	path('jobs/', jobs_view, name='jobs'),
	path('job/<int:pk>', jobDetail, name='jobDetail'),
	path('job/delete/<int:pk>', jobDelete, name='jobDelete'),
	path('job/<int:jid>/resume/delete/<int:rid>', resumeDelete, name='resumeDelete')
	
]

profiles/urls.py
from django.urls import path, re_path

from .views import (
	signup, ProfileUpdateView, account_activation_sent_view, account_activate
)

app_name = 'profiles'

urlpatterns = [
	path('', signup, name='profile-signup'),
	path('<int:pk>/edit/', ProfileUpdateView.as_view(), name='profile-edit'),
]

urlpatterns += [
	path('account-activation-sent/', account_activation_sent_view, name='account-activation-sent'),
	path('activate/<uidb64>/<token>/', account_activate, name='activate'),
]

users/urls.py
from django.urls import path

from .views import home_view, signup_view

app_name = "users"

urlpatterns = [
    path('', home_view, name='home'),
    path('signup/', signup_view, name='sign-up'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('', include('jobs.urls', namespace='jobs')),
    path('profile/', include('profiles.urls', namespace='profiles')),
]

urlpatterns += [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Resume_Ranker  | {% block title %}{% endblock %}</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'boxicons-2.0.7/css/boxicons.min.css'  %}" rel="stylesheet">
    <!-- For datatables -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css"></style>
    <script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js" defer></script>
</head>

  <body>

      {% include "navbar.html" %}

      <!-- Start your project here-->
      <div style="height: 100vh" class="container">

        {% block content %}

         

        {% endblock %}
      </div>
      <!-- /Start your project here-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    {% block script %}
    {% endblock %}
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
</body>

</html>

templates/navbar.html
<div class="c">
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark secondary-color mb-5">


    <!-- Navbar brand -->
    <img src="../static/img/logo/logo1.PNG" class="img-rounded" alt="logo" 
    height="3.5%"
    width="3.5%"
    style="display:block ;  margin-left: auto; margin-right:2% ;"
    >
    <a class="navbar-brand" href="{% url 'users:home' %}">ResumeRanker</a>

    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'users:home' %}">Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            {% endif %}
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'jobs:jobs' %}">Jobs</a>
            </li>
            {% endif %}
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:profile-edit' user.profile.id %}">Profile</a>
            </li>
            {% endif %}

        </ul>
        <!-- Links -->

        <!-- login and logout buttons -->
        <div class="my-1 mr-3">
            {% if user.is_authenticated %}
            <!-- user icon -->
                <div class="white-text">
                   <i class="fa fa-user" aria-hidden="true"></i>
                   {{ request.user }}
                   </div>
                
        </div>
        <div class="my-1 mr-3">
                <a class="btn btn-outline-white btn-md my-2 my-sm-0 ml-3" href="{% url 'logout' %}">Logout</a>
                </div>
            {% else %}
            <div class="my-1 mr-3">
                <a class="btn btn-outline-white btn-md my-2 my-sm-0 ml-3" >About</a>
                <a class="btn btn-outline-white btn-md my-2 my-sm-0 ml-3" >Contact</a>        
                <a class="btn btn-outline-white btn-md my-2 my-sm-0 ml-3" href="{% url 'login' %}">Sign In</a>
                <a class="btn btn-outline-white btn-md my-2 my-sm-0 ml-3" href="{% url 'profiles:profile-signup' %}">Sign Up</a>           
            {% endif %}
        </div>        
    </div>
    <!-- Collapsible content -->



</nav>
<!--/.Navbar-->
</div>